    <div class="container-fluid">
        <div class="row" style="padding-top: 80px;padding-bottom: 80x;padding-right: 0;padding-left: 0;">
            <div class="col space">
                <div class="carousel slide carousel-fade" data-ride="carousel" data-interval="5000" data-keyboard="false" id="carousel-1">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active"><img class="w-100 d-block" src="img/set_ad.jpg" alt="Slide Image"></div>
                        <div class="carousel-item"><img class="w-100 d-block" src="img/ad1.jpg" alt="Slide Image"></div>
                    </div>
                    <div class="d-none"><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button"
                            data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a></div>
                </div>
                <div>
                    <!--form method="get" action="<?php #echo $this->url('search');?>"-->
                    <form method="post">
                    <div class="input-group" style="padding-top: 30px;">
                        <div class="input-group-prepend"></div><input class="form-control" type="text" name='search' placeholder="e.g Relevance of town planning in national development">
                        <div class="input-group-append"><button type="submit" name="btnSearch" class="btn btn-primary" role="button"><i class="fa fa-search"></i>&nbsp; Search</button></div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>