
                        <div>
                            <form method="post" action="<?php echo $this->url('dashboard');?>">
                                <div class="form-group" style="background-color: #116d16;margin-top: 20px;padding: 5px;">
                                    <div class="input-group"><input name="search" value="<?php echo $this->item;?>" class="form-control" type="text" placeholder="e.g Architecture for beginners">
                                        <div class="input-group-append"><button class="btn btn-primary" type="submit" name='searchDoc'><i class="fa fa-search"></i>&nbsp; Search</button></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="table-responsive">
                                    <div id='r'></div>
                                        <table class="table">
                                            <thead>
                                                <tr style="padding: 5px;background-color: #116d16;color: rgb(247,248,249);">
                                                    <th><input type="checkbox"></th>
                                                    <th>Title</th>
                                                    <th style="max-width: 400px;">Note</th>
                                                    <th>Reg Date</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if(isset($this->result)){
                                                $result=$this->result;#paginator;
                                                $i=1;
                                                
                                                foreach ($result as $document){
                                            ?>
                                                <tr>
                                                    <td><input type="checkbox" id='d<?php echo $i;?>' name='d<?php echo $i;?>'><input type='hidden' id='c<?php echo $i;?>' value="<?php echo $document->sn;?>"></td>
                                                    <td><a href="<?php echo $document->filepath;?>" target="_new"><strong><?php echo $document->title;?></strong></a>
                                                        <div class="text-left" style="font-size: 13px;color: rgb(176,178,180);"><small style="margin-right: 5px;"><i class="fa fa-book"></i>&nbsp;<?php echo $document->genre;?></small><small style="margin-right: 5px;"><i class="fa fa-file-pdf-o"></i>&nbsp;<?php echo $document->filetype;?></small><small style="margin-right: 5px;"><i class="fa fa-paste"></i>&nbsp;<?php echo $document->pagenumber;?> pages</small>
                                                            <small
                                                                style="margin-right: 5px;"><i class="fa fa-eye"></i>&nbsp;last viewed on <?php echo $document->lastview;?></small>
                                                        </div>
                                                    </td>
                                                    <td><?php echo substr($document->note, 0, 50);?>....<br></td>
                                                    <td><?php echo $document->regdate;?></td>
                                                    <td>
                                                        <div style="font-size: 16px;"><a href="<?php echo $this->url('edit')."?id=".$document->sn;?>" style="font-size: 16px;"><i class="fa fa-edit"></i></a></div>
                                                    </td>
                                                </tr>
                                            <?php 
                                                $i++;
                                                }
                                            }
                                            ?>
                                            </tbody>
                                        </table>
                                        <?php 
                                            $j=$i-1;
                                            echo "<input type='hidden' id='totalrecord' value='$j'>";
                                        ?>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="btn-group" role="group"><a href="<?php echo $this->url('addnew');?>" class="btn btn-success" type="button"><i class="fa fa-plus-circle"></i>&nbsp;Add New Material</a><button class="btn btn-danger" type="button" onclick="mvc_remove_documents()"><i class="fa fa-remove"></i>&nbsp;Remove Material</button></div>
                        
                        <?php
                        // add at the end of the file after the table
                        echo $this->paginationControl(
                        // the paginator object
                        $this->result,
                        // the scrolling style
                        'sliding',
                        // the partial to use to render the control
                        'partial/paginator.phtml',
                        // the route to link to when a user clicks a control link
                        array(
                        'route' => "dashboard",
                        'data'=>"$this->item"
                        )
                        );
                    ?>
