<?php if ($this->pageCount): ?>
<nav style="margin-top: 20px;margin-right: 40%;margin-left: 40%;width: 20%;">
    <ul class="pagination">
    <!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
        <li class="page-item"><a href="<?php echo $this->url($this->route); ?>?search=<?php echo $data;?>&page=<?php echo $this->previous; ?>" class="page-link" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        <?php else: ?>
        <li class="page-item"><a class="page-link disabled" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        <?php endif;?>
        <!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
        <li class="page-item"><a href="<?php echo $this->url($this->route);?>?search=<?php echo $data;?>&page=<?php echo $page; ?>" class="page-link"><?php echo $page;?></a></li>
        <?php else:?>
        <li class="page-item active"><a class="page-link"><?php echo $page;?></a></li>
        <?php endif;?>
        <?php endforeach; ?>
        <!-- Next page link -->
		<?php if (isset($this->next)): ?>
        <li class="page-item"><a href="<?php echo $this->url($this->route); ?>?search=<?php echo $data;?>&page=<?php echo $this->next; ?>" class="page-link" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        <?php else: ?>
        <li class="page-item disabled"><a class="page-link" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        <?php endif;?>
    </ul>
</nav>
<?php endif;?>